server:
  port: 9001
spring:
  application:
    name: ribbin-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

# 仪表盘显示
management:
  endpoints:
    web:
      exposure:
        include: '*'
